### PR TITLE
Make serialization round trip of Event work

### LINKED ISSUE #584: Exception to deserialize 'com.spotify.docker.client.messages.Event'
## Description

I'm trying to serialize events from Docker to send for a monitoring tool. I can serialized an event to json, but when I try to deserialize  arise an exception : `Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: For input string: "2017-01-11T06:43:34.000+0000" (through reference chain: com.spotify.docker.client.messages.Event["time"])`

## How to reproduce
```
package br.cin.gfads.adalrsjr1.docker_monitor;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.spotify.docker.client.DefaultDockerClient;
import com.spotify.docker.client.DockerClient;
import com.spotify.docker.client.EventStream;
import com.spotify.docker.client.ObjectMapperProvider;
import com.spotify.docker.client.messages.Event;

public class App 
{
	private static final Logger log = LoggerFactory.getLogger(App.class);
	
    public static void main( String[] args ) throws Exception
    {
    	DockerClient docker = DefaultDockerClient.fromEnv().build();
    	DefaultDockerClient.builder()
    					   .uri("localhost:2376")
    					   .connectionPoolSize(1)
    	                                   .build();
    	
    	EventStream eventStream = docker.events();
    	while(eventStream.hasNext()) {
    		Event ev = eventStream.next();
    		
    		ObjectMapperProvider omp = new ObjectMapperProvider();
    		ObjectMapper mapper = omp.getContext(Event.class);
    		
    		String json = mapper.writerWithView(Event.class).writeValueAsString(ev);
    		
    		Event ev2 = mapper.getFactory().createParser(json).readValueAs(Event.class);
//    		Event ev2 = mapper.readerFor(Event.class).readValue(json); // also not working
    		log.info(ev2+"");
    	}
    	
    	docker.close();
    	
    }
}
```

## What do you expect
I expect something like this:

`Event{status=null, id=null, from=null, type=NETWORK, action=disconnect, actor=Actor{id=hvb6mpc8t4iu7j85vu27sb1n6, attributes={container=a2ceade7f529694723695256c5d04b135e5573f9b05c597448e1a8d171a22231, name=ingress, type=overlay}}, time=Wed Jan 11 03:52:33 GFT 2017, timeNano=1484117553094885100}`

## What happened instead
`Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: For input string: "2017-01-11T06:43:34.000+0000" (through reference chain: com.spotify.docker.client.messages.Event["time"])`

## Software:

- `docker version`:
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      linux/amd64
 Experimental: true
- Spotify's docker-client version: 7.0.0

## Full backtrace

```text
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: For input string: "2017-01-11T06:54:27.000+0000" (through reference chain: com.spotify.docker.client.messages.Event["time"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1475)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:463)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:377)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1100)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:131)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3674)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1996)
	at com.fasterxml.jackson.core.JsonParser.readValueAs(JsonParser.java:1511)
	at br.cin.gfads.adalrsjr1.docker_monitor.App.main(App.java:39)
Caused by: java.lang.NumberFormatException: For input string: "2017-01-11T06:54:27.000+0000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:589)
	at java.lang.Long.parseLong(Long.java:631)
	at com.spotify.docker.client.jackson.UnixTimestampDeserializer.deserialize(UnixTimestampDeserializer.java:47)
	at com.spotify.docker.client.jackson.UnixTimestampDeserializer.deserialize(UnixTimestampDeserializer.java:36)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:461)
	... 8 more
```

### PR DESCRIPTION
**Pull request by davidxia**
fixes #584

### CODE REVIEW

File: src/test/java/com/spotify/docker/client/jackson/UnixTimestampSerializerTest.java [hunk 1]
```diff
@@ -0,0 +1,60 @@
...
+import com.spotify.docker.client.ObjectMapperProvider;
+
+import java.util.Date;
+
+import org.junit.Test;
+
+public class UnixTimestampSerializerTest {
+
+  private static final ObjectMapper OBJECT_MAPPER =
+      new ObjectMapperProvider().getContext(UnixTimestampSerializerTest.class);
```
Comment (mattnworb) [inline src/test/java/com/spotify/docker/client/jackson/UnixTimestampSerializerTest.java]: not directly related but we should just make `ObjectMapperProvider.objectMapper()` public

File: src/test/java/com/spotify/docker/client/messages/EventTest.java [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    final Event event = Event.create("create", "foo", "nginx", Event.Type.CONTAINER, "create",
+        Event.Actor.create("bar", ImmutableMap.of("image", "nginx", "name", "docker-nginx")),
+        new Date(1487356000), 100L);
+
+    final ObjectMapperProvider omp = new ObjectMapperProvider();
+    final ObjectMapper mapper = omp.getContext(Event.class);
+
+    final String json = mapper.writerWithView(Event.class).writeValueAsString(event);
+
+    final Event event2 = mapper.getFactory().createParser(json).readValueAs(Event.class);
```
Comment (mattnworb) [inline src/test/java/com/spotify/docker/client/messages/EventTest.java]: why do you need `mapper.writerWithView(Event.class).writeValueAsString(event)` instead of just `mapper.writeValueAsString(event)`?

same question for `mapper.getFactory().createParser(json).readValueAs(Event.class)` instead of `mapper.readValue(json, Event.class)`?

Comment (davidxia) [inline src/test/java/com/spotify/docker/client/messages/EventTest.java]: Good catch.

File: src/test/java/com/spotify/docker/client/jackson/UnixTimestampSerializerTest.java (hunk 1 above)
Comment (davidxia) [inline src/test/java/com/spotify/docker/client/jackson/UnixTimestampSerializerTest.java]: The `ObjectMapperProvider` is a bit silly. The `Json` class here is better https://github.com/spotify/helios/blob/master/helios-client/src/main/java/com/spotify/helios/common/Json.java because it's all static methods using a private ObjectMapper delegate.

Comment (mattnworb) [inline src/test/java/com/spotify/docker/client/jackson/UnixTimestampSerializerTest.java]: agreed. I think it would make sense to refactor it so that there is still a static way to get an instance of an ObjectMapper, but also still something that implements jersey's `ContextResolver` - just to make all these tests look less weird in regards to how they get an ObjectMapper
