### PR TITLE
Fixed #608

### LINKED ISSUE #608: Test testStorageOpt fails for docker 1.12.1
## Description

When doing a maven test on docker 1.12.1 (via Travis), the same test fails on multiple Pull Requests including #602 and #604 

## How to reproduce

mvn clean test

## What do you expect

This test should pass. 

## What happened instead

Instead, the error states that aufs does not support --storage-opt parameters.
```
  testStorageOpt(com.spotify.docker.client.DefaultDockerClientTest): Request error: POST unix://localhost:80/containers/create?name=2c27144a8128f2e1-5600b1b4b777125a: 500, body: {"message":"--storage-opt is not supported for aufs"}(..)
```

## Software:

- `docker version`: 1.12.1
- Spotify's docker-client version: 7.0.3-SNAPSHOT

## Full backtrace

```text
testStorageOpt(com.spotify.docker.client.DefaultDockerClientTest)  Time elapsed: 0.475 sec  <<< ERROR!
com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/create?name=2c27144a8128f2e1-5600b1b4b777125a: 500, body: {"message":"--storage-opt is not supported for aufs"}
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2122)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2073)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:583)
	at com.spotify.docker.client.DefaultDockerClientTest.testStorageOpt(DefaultDockerClientTest.java:3996)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1020)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by loicortola**
Fixed storage-opt test:

when aufs is the default storage driver, the storage-opt option is not available.
Changed test to only be ran when storage driver is not aufs.

See explanations in this stackOverflow post:
http://stackoverflow.com/questions/39890463/docker-storage-opts-and-aufs-storage-driver

### CODE REVIEW

File: src/test/java/com/spotify/docker/client/DefaultDockerClientTest.java [hunk 1]
```diff
@@ -340,6 +340,11 @@ private void requireDockerApiVersionAtLeast(final String required, final String
     assumeTrue(msg, dockerApiVersionAtLeast(required));
   }
 
+  private boolean storageDriverNot(String driver) throws Exception {
```
Comment (johnflavin) [inline src/test/java/com/spotify/docker/client/DefaultDockerClientTest.java]: I would rather see this method changed from `boolean storageDriverNot(String driver)`, which checks the version and returns a `boolean`, to `void requireStorageDriverNotAufs()` which hard-codes a check of the driver against `"aufs"` and passes that to `assumeFalse(...)`. That way in your test, you don't have to wrap everything in `if (storageDriverNot("aufs")) {...}`, your test can just call `requireStorageDriverNotAufs()` and if the test runner sees that the assumption is invalid it will exit the test. See, for example, `requireDockerApiVersionAtLeast(...)` and `requireDockerApiVersionLessThan(...)` which do this same thing.

Comment (loicortola) [inline src/test/java/com/spotify/docker/client/DefaultDockerClientTest.java]: Sounds good. Will do it right away so we can merge this ASAP. Thanks for the feedback
