### PR TITLE
Fix event filtering with spaces

### LINKED ISSUE #626: Filters for events containing spaces never match
## Description

Asking Docker to filter for events that contain a space, such as `health_status: healthy`, will never match.

This works using the Docker CLI or Docker API directly.

## How to reproduce

```java
EventStream eventStream = docker.events(
    EventParam.event("health_status: healthy")
);
eventStream.hasNext(); // Will never fire
```

This minimal Dockerfile will generate 1 `health_status: healthy` message after 3 seconds; re-run it to generate more:

```
FROM busybox:1.26

HEALTHCHECK --interval=1s --timeout=1s --retries=3 CMD true

CMD ["sleep", "10"]
```

## What do you expect

Events with action "health_status: healthy" will match and be returned by `next()`.

## What happened instead

Events are not matched.

## Software:

```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Spotify's docker-client version: 7.0.2

---

Briefly stepping through the code, it looks like the filter arguments are being double URL encoded before being sent out:

```
Spotify Docker Client sends:
/events?filters=%7B%22event%22%3A%5B%22health_status%3A%2Bhealthy%22%5D%7D
/events?filters={"event":["health_status:+healthy"]}

This works with the API:
/events?filters=%7B%22event%22%3A%5B%22health_status%3A%20healthy%22%5D%7D
/events?filters={"event":["health_status: healthy"]}

This also works:
/events?filters=%7B%22event%22%3A%5B%22health_status%3A+healthy%22%5D%7D
/events?filters={"event":["health_status: healthy"]}
```

### PR DESCRIPTION
**Pull request by davidxia**
fixes #626

### CODE REVIEW

File: src/main/java/com/spotify/docker/client/DefaultDockerClient.java [hunk 1]
```diff
@@ -495,15 +495,16 @@ public Info info() throws DockerException, InterruptedException {
...
-   * @param unencoded A string that may contain characters not allowed in URLs
+   * @param unencoded A string that may contain characters not allowed in URL query parameters.
    * @return URL-encoded String
    * @throws DockerException if there's an UnsupportedEncodingException
    */
   private String urlEncode(final String unencoded) throws DockerException {
     try {
-      return URLEncoder.encode(unencoded, UTF_8.name());
+      final String encode = URLEncoder.encode(unencoded, UTF_8.name());
+      return encode.replaceAll("\\+", "%20");
```
Comment (davidxia) [inline src/main/java/com/spotify/docker/client/DefaultDockerClient.java]: Is there a better way? I googled a lot for something that specifically encodes for URL query params but couldn't find anything that didn't require an extra dep.
